### ISSUE TITLE
Could you include an example of how to generate a client?

### ISSUE THREAD

**Issue by toddobryan** [upstart-commerce/sbt-openapi-generator#10]
I have an OpenAPI yaml file, I've set up the plugin, but I'm not sure what I should do to generate the source code. I'm also not sure that my build.sbt is correct.

Here's what I have:
```
import sbt.Keys.scalaVersion

lazy val root = (project in file("."))
  .enablePlugins(OpenAPIGeneratorPlugin)
  .settings(
    name := "food-data-central",
    version := "0.1",
    scalaVersion := "2.13.2",
    openapiInputSpec := file("fdc.yaml").toURI,
    openapiGeneratorName := "scala-akka"
  )
```

If I'm missing some documentation, feel free to just point me to it.

Thanks!

**Comment by YanDoroshenko** [comment]
Hey man. Sorry, the README was a bit outdated. Now it rightfully says that after you're done with configuration, you should run `openapiGenerate` to generate the sources.
