### ISSUE TITLE
system properties do not accept non-map values

### ISSUE THREAD

**Issue by jwgcooke** [upstart-commerce/sbt-openapi-generator#5]
The current system properties that may need to be set include "models" which is not a map key/value, just a string.  (i.e. -Dmodels) and I do not see a way to address this in the current map structure

**Comment by YanDoroshenko** [comment]
System properties is a map. `-Dmodels` syntax supported by the openapi-generator-cli is a shortcut for `-Dmodels=""`, this substitution happens in an untyped and non-transparent manner inside the OpenAPI generator. In the SBT plugin you have to specify `"$key" -> ""` in the system properties map to achieve the same result.
