### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mkubala** [upstart-commerce/sbt-openapi-generator#8]
Hi guys!

I'd appreciate if you could release a new version of the SBT plugin which uses the recently updated openapi-generator library. Revision 4.3.0 brings a couple of major fixes for scala-akka generator (just to let you know about how important they are - one is the fix for missing bodies in PATCH requests, another brings support for auth tokens).

Thanks!

**Comment by YanDoroshenko** [comment]
Ask and it will be given to you. Version 0.1.2 is [here](https://bintray.com/beta/#/upstartcommerce/generic/sbt-openapi-generator).

**Comment by mkubala** [comment]
That was really fast! Thanks!
